### ISSUE TITLE
Frames produced with QWatson are not compatible with stock Watson

### ISSUE THREAD

**Issue by jnsebgosselin** [jnsebgosselin/qwatson#37]
In QWatson, a custom version of Watson is used to support adding comments to frames. the addition of this `comment` field in the `json` file (see PR #1) is the reason of this non compatible issue. When the `frame` with the current content is loaded with Watson :
```json
[
 [
  1528993380,
  1529026320,
  "project1_renamed",
  "802d6afc5d03410b8cf91cdf15ee2b33",
  [
   "tag1",
   "tag2",
   "tag3"
  ],
  1529426002
 ]
]
```

The following error occur when trying to access the frame :

```python traceback
Traceback (most recent call last):

  File "<ipython-input-4-baa54319e689>", line 1, in <module>
    frame = client.frames[0]

  File "D:\watson\watson\watson.py", line 174, in frames
    self.frames = self._load_json_file(self.frames_file, type=list)

  File "D:\watson\watson\watson.py", line 180, in frames
    self._frames = Frames(frames)

  File "D:\watson\watson\frames.py", line 76, in __init__
    rows = [Frame(*frame) for frame in frames]

  File "D:\watson\watson\frames.py", line 76, in <listcomp>
    rows = [Frame(*frame) for frame in frames]

TypeError: __new__() takes from 5 to 7 positional arguments but 8 were given
```
This means QWatson and Watson CLI cannot be used concurrently for the moment, not until the support to comments is added into Watson.

**Comment by jnsebgosselin** [comment]
After a quick testing, QWatson is backward compatible with Watson frames... I was missing a `]` at the end of the file I was using for testing XD.

**Comment by jnsebgosselin** [comment]
Let's make it so that QWatson doesn't use the default config directory of Watson, so that if someone uses QWatson and doesn't like it and want to revert using Watson CLI, it doesn't messes up it's frames database.
